name: bank_al_dawa
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bot_toast: ^4.0.2
  dio: ^4.0.6
  get: ^4.6.5
  objectbox: ^1.5.0
  objectbox_flutter_libs: ^1.5.0
  shimmer: ^2.0.0
  intl: ^0.17.0
  path_provider_android: ^2.0.15
  path_provider: ^2.0.11
  path: ^1.8.1
  equatable: ^2.0.3
  google_fonts: ^3.0.0
  flutter_inset_box_shadow: ^1.0.8
  gradient_widgets: ^0.6.0
  search_choices: ^2.0.20
  octo_image: ^1.0.0
  cached_network_image: ^3.2.1
  fl_chart: ^0.55.0
  card_swiper: ^2.0.4
  add_2_calendar: ^2.1.3
  table_calendar: ^3.0.6
  image_picker: ^0.8.5+3
  flutter_slidable: ^1.3.0
  connectivity_plus: ^2.3.5
  url_launcher: ^6.1.5
  excel: 2.0.0-null-safety-3
  lottie: ^1.3.0
  flutter_svg: ^1.0.3
  permission_handler: ^9.2.0
  device_info: ^2.0.3
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  firebase_app_installations: ^0.1.1+3
  flutter_local_notifications: ^9.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  objectbox_generator: ^1.5.0

  flutter_lints: ^2.0.1

flutter:
  assets:
   - assets/images/no_results.svg 
   - assets/lottie/welcome.json
   - assets/images/ic_launcher.png
  uses-material-design: true
